### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ventrio** [Kon-UU/Ro-Sniper-python#10]
![image](https://user-images.githubusercontent.com/65818729/156910791-3fc76755-59db-440e-b110-1f004ddb56ee.png)
(this is what happens when i open start)
and when i open main it just instantly closes

**Comment by Kon-UU** [comment]
![image](https://user-images.githubusercontent.com/92216445/156911722-9e54d186-3ab3-4c9f-8263-fa6353824180.jpeg)

**Comment by Kon-UU** [comment]
Type pip install python-dotenv at cmd

**Comment by ventrio** [comment]
![image](https://user-images.githubusercontent.com/65818729/156921408-9d470955-e574-49b8-9358-68a68ccab25c.png)
