### ISSUE TITLE
bug in creating catche file 

### ISSUE THREAD

**Issue by ventrio** [Kon-UU/Ro-Sniper-python#11]
![image](https://user-images.githubusercontent.com/65818729/156921430-2f92e50a-7e6d-4b0a-8ad0-504d817d5e5e.png)

**Comment by ventrio** [comment]
created cache folder manually, now its working but the sniper isnt printing anything, when i run it?

**Comment by Kon-UU** [comment]
create 'caches' folder not 'cache'

**Comment by ventrio** [comment]
oh i did but, when i open sniper it isnt printing anything when i press option 2
