### ISSUE TITLE
isnt printing anything on sniper 

### ISSUE THREAD

**Issue by ventrio** [Kon-UU/Ro-Sniper-python#12]
when i use sniper option it doesnt print anything.

**Comment by ventrio** [comment]
![image](https://user-images.githubusercontent.com/65818729/156921826-275726eb-a0fa-4211-9bbc-91b2f2bcb8f7.png)

**Comment by ventrio** [comment]
![image](https://user-images.githubusercontent.com/65818729/156921998-90168626-fb0f-459a-99b9-81f3cb7bbcdc.png)

**Comment by Kon-UU** [comment]
Bad proxy
