### ISSUE TITLE
Error + question

### ISSUE THREAD

**Issue by Lancmo** [Kon-UU/Ro-Sniper-python#14]
When adding multiple IDs do I need to do a comma after each ID accept for the last one?

Example:

00000001,
00000002,
00000003,
00000004,
00000005

Also, does having more IDs slow the program down?

**Comment by Lancmo** [comment]
When running the program on cache mode, it runs until I then get this error below, how do I fix this?
![image](https://user-images.githubusercontent.com/43474283/157296281-9f67d6b3-1580-4856-b5cd-c1cf916099b5.png)

**Comment by Lancmo** [comment]
?

**Comment by ventrio** [comment]
no

**Comment by Lancmo** [comment]
wdym no?
