### ISSUE TITLE
Given Id not a limited and also question

### ISSUE THREAD

**Issue by signata** [Kon-UU/Ro-Sniper-python#16]
What does cache do compare to sniping and how do I know sniping is working? It just says Last 5 Min Checked 16, Last 5 Min Error2153, Total Checks 16 every 5 mins in the command prompt. Also when I use Cache mode it says given mod ID not a limited even though it is. I don't know the difference between cache and sniping which is better

**Comment by ripbozot** [comment]
I have the same problem, when I cache it says that item is not limited.Caching means its checking the inv of all users I think and make the .txt files of item ids, this is in order for the program to work. Sniping mode is when you have thei tems cached and it price checks items
