### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ripbozot** [Kon-UU/Ro-Sniper-python#18]
It says the item id is not limited but it is 
![image](https://user-images.githubusercontent.com/95044149/161347937-1dc29519-5394-434c-b400-274e0fb0d75d.png)

**Comment by Kon-UU** [comment]
Maybe ratelimited or wrong limited id

**Comment by ripbozot** [comment]
its not the wrong limited id ive checked this id is a limited 2620506085 so if its ratelimited how to fix it?
