### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by ItzzBlueSky** [Kon-UU/Ro-Sniper-python#2]
![obraz_2022-03-03_113230](https://user-images.githubusercontent.com/100841043/156547217-7ea39112-4113-43c1-ae6b-7aab1e144f6d.png)

No caches file ??

**Comment by ItzzBlueSky** [comment]
[image: image.png]what folder do i need to create>?

czw., 3 mar 2022 o 11:34 Kon-UU ***@***.***> napisał(a):

**Comment by Kon-UU** [comment]
caches

**Comment by ItzzBlueSky** [comment]
![image](https://user-images.githubusercontent.com/100841043/156548219-cd47dc72-998d-459b-8cec-2737b2c75412.png)
like this ?

**Comment by ItzzBlueSky** [comment]
![image](https://user-images.githubusercontent.com/100841043/156548263-85a58123-89f2-4232-bd50-80bc46c457f5.png)

still same thing

**Comment by Kon-UU** [comment]
You should cache it first I'll change readme.md soon I'm at school now

**Comment by ItzzBlueSky** [comment]
i dont know what u mean by cache it first ;dd, btw sorry for bothering while in school, just wanted to know how to fix yk

**Comment by Kon-UU** [comment]
If u have a bit of background about python u can fix it by yourself currently i dont have time to fix your own problem and it is not even a problem

**Comment by ItzzBlueSky** [comment]
i mean it says to create folder, its not hard, but i created folder called caches and nothing happens its not even getting detected that the folder is created

**Comment by ItzzBlueSky** [comment]
alr i fixed all but 1 more question 
![image](https://user-images.githubusercontent.com/100841043/156613973-0fde37c3-7fc1-4c31-9a0c-3c6a0c3e2855.png)
is this anything that i should be aware of ?
