### ISSUE TITLE
Program just closes

### ISSUE THREAD

**Issue by GamingSteroids** [Kon-UU/Ro-Sniper-python#5]
I open the program and not even a second passes it just closes with no errors. How can I fix this?

**Comment by ColegoneCrazy** [comment]
1. Open Command Promt
2. Copy the address for the Ro-sniper-main file (view ima
![Screenshot (15)](https://user-images.githubusercontent.com/87844245/156664280-b77716a7-e7d8-48ef-abfb-0d376b005d17.png)
ge)
3. in command promt, type cd and then ctrl v, then hit enter
4. type python main.py
5. If you made the cache folder then push 1 for this step, if you have already cached then push 2 to start sniping
How to make cache folder: Import a folder and rename it as "caches"
6. After you press 2 it should be sniping but i had a bug where it doesn't work, so imma wait for a reply to my pull

**Comment by IAmHard247** [comment]
https://imgur.com/xgVcVVn

I get this error. Or am I doing something wrong?

**Comment by ColegoneCrazy** [comment]
> https://imgur.com/xgVcVVn
> 
> I get this error. Or am I doing something wrong?

Cookie is invalid

**Comment by IAmHard247** [comment]
Is it a cookie for my roblox account or what?

**Comment by IAmHard247** [comment]
https://imgur.com/a/66RhRPY 

I changed the cookie and I get this now.

**Comment by Kon-UU** [comment]
install requests module

**Comment by IAmHard247** [comment]
Install what kind of modules?

**Comment by Kon-UU** [comment]
Think u dont have main.py in that folder just search it on google I'm 100% sure you can fix it by yourself

**Comment by Lancmo** [comment]
![image](https://user-images.githubusercontent.com/43474283/156687956-ff8a06f4-6c27-4799-87a6-0953944f8ce8.png)

**Comment by IAmHard247** [comment]
Yeah, it will fix the error but I keep getting a cookie error. Even though its the correct cookie.

**Comment by IAmHard247** [comment]
"Last 5 Min Checked 0, Last 5 Min Error22015, Total Checks 0" I keep getting this error though.

**Comment by GamingSteroids** [comment]
So, will someone help me? XD

**Comment by Kon-UU** [comment]
Bad proxy

**Comment by GamingSteroids** [comment]
Where can I get decent proxies for decent price?
