### ISSUE TITLE
Whenever I open the "main.py" program it closes almost instantly.

### ISSUE THREAD

**Issue by Lancmo** [Kon-UU/Ro-Sniper-python#6]
Whenever I open the "main.py" program it closes almost instantly.

I know for a fact I set up everything correctly as I followed the directions that were provided in the "README" text file.

Discord: LancmoV2#8401

**Comment by IAmHard247** [comment]
Look at the thread I have created.

**Comment by Lancmo** [comment]
> 

I did and I tried the solutions in there and none of them worked.

**Comment by IAmHard247** [comment]
Do you have Python installed and the python-dotenv?

**Comment by Lancmo** [comment]
![image](https://user-images.githubusercontent.com/43474283/156686904-0bc383a6-03dc-4242-9a4a-3c443901a274.png)

**Comment by IAmHard247** [comment]
Yeah, I keep getting that issue also. I already took a picture and asked in my Issue thread.

**Comment by Kon-UU** [comment]
It is not a bug gonna close it

**Comment by Lancmo** [comment]
How do I fix it? Im having a problem with this and many others are too. No one knows how to fix it and you're not helping anyone

**Comment by Kon-UU** [comment]
I only have 10~20min of freetime in day so I can't help everyone and it's open sourced so u can fix it by yourself.
