### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by GamingSteroids** [Kon-UU/Ro-Sniper-python#9]
Where can I get good proxies for a decent price? Because the program gives me this

 "Please create caches folder ! (1) Caching, (2) Sniping2
Last 5 Min Checked 0, Last 5 Min Error22748, Total Checks 0".

**Comment by Kon-UU** [comment]
Stop asking this shit

**Comment by GamingSteroids** [comment]
I'm just trying to get help and finally get this shit to work.

**Comment by GamingSteroids** [comment]
You just said get good proxies and it like I know where I can get the "Good Proxies"

**Comment by Kon-UU** [comment]
It's not about the program just find it yourself I don't wanna help you kid
